config/routes.rb
Rails.application.routes.draw do
  get 'questions/new'
  get 'sessions/new'
  
  root 'pages#index'
  get 'pages/help'
  
  resources :users do
    member do
      get :following,:followers
    end
  end
  resources :questions
  resources :categories
  resources :answers
  resources :relationships
  resources :requests
  
  #get    'requests/new'
  #post   '/requests', to: 'requests#create'
  #, only: [:create, :destroy]
  
  get    'favorites/index'
  post   '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  root 'question#index'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  
  belongs_to :user
  belongs_to :question
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: 'user', dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :questions
  #has_many :question_categories
  #has_many :questions, through: :question_categories
  #accepts_nested_attributes_for :question_category
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ApplicationRecord
  validates :user_id, presence: true
  validates :question, presence: true
  #validates :category_id, presence: true
  
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :requests, dependent: :destroy
  #has_many :request_users, through: :requests, source: 'user'
  #has_many :question_categories
  #has_many :categories, through: :question_categories
  #accepts_nested_attributes_for :question_categories
end

app/models/question_category.rb
class QuestionCategory < ApplicationRecord
    validates :question_id, presence: true
    validates :category_id, presence: true
    
    belongs_to :category
    belongs_to :question
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, format: { with: /[^\s]@[^\s]\.[^\s]/ }
  validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\Z/i }
  validates :password_confirmation, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\Z/i}
  
  has_secure_password
  
  has_many :questions
  has_many :answers
  has_many :favorites
  has_many :favorite_answers, through: :favorites, source: 'answer'
  has_many :requests
  has_many :request_questions, through: :requests, source: 'question'
  has_many :active_relationships, class_name: "Relationship",
                    foreign_key:"follower_id",
                    dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                    foreign_key:"followed_id",
                    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships,source: :follower
  
  
  
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end
  
  def create
    @answer = current_user.answers.new(answer_params)
    
    if @answer.save
      redirect_to question_path(@answer.question_id), success: '回答を投稿しました'
    else
      flash.now[:danger] = '入力内容を確認していください'
      render :new
    end
  end
  
  def destroy
    answer = Answer.find(params[:id])
    #byebug
    if answer.destroy
      redirect_to question_path(answer.question_id), success: '削除しました'
    else
      flash.now[:danger] = '削除できませんでした'
      render :new
    end
  end

  
  private
  def answer_params
    params.require(:answer).permit(:user_id, :question_id, :answer)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @question = Question.all
  end
 
  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    
    if @question.save
      redirect_to questions_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end
  
  def show
    @question = Question.find(params[:id])
  end
  
  def destroy
    @question = Question.find(params[:id])
    
    if @question.destroy
     
      redirect_to questions_path, success: '削除しました'
    else
      flash.now[:danger] = '削除できませんでした'
      render :new
    end
  end
  
  private 
  def question_params
    params.require(:question).permit(:question, :category_id, :category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to root_path, success: '登録が完了しました'
      else
        flash.now[:danger] = "登録に失敗しました"
        render :new
      end
  end
  
  def show
    @user = User.find(params[:id])
    #@request = Request.find(params[:user][:id])
    #@user = User.find(params[:user][:id])
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/questions/index.html.erb
<div class="question-index-wrapper">
  <div class="container" %>
    <% @question.each do |question| %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="question-index-single">
          <p class="question-author">
            <%= link_to question.user.name , user_path(question.user_id) %>
          </p>
          <p class= "question-category">
            <%= question.category.category %>
          </p>
          <div class= "question-text">
            <%= simple_format(question.question) %>
          </div>
          <div class= "details">
            <%= link_to '詳細', question_path(question.id), class: 'btn btn-block btn-white' %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<div class="question-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for @question do |f| %>
        <div class="form-group">
          <div class="category">
            <%= f.label :category %>
          </div>
            <%= f.collection_select :category_id, Category.all, :id, :category %>
        </div>
        <div class="form-group">
          <%= f.text_area :question,:size=>"60x20", class: "form-control"  %>
        </div>
          
          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="question-show-wrapper">
  <div class="conrainer">
    <div class="row">
    　<div class="question-details">
      　<div class="col-md-6 col-md-offset-3">
          <div class="question-index-single">
            <p class="question-author">
              <%= link_to @question.user.name , user_path(@question.user_id) %>
            </p>
            <p class= "question-category">
              <%= @question.category.category %>
            </p>
            <div class= "question-text">
              <%= simple_format(@question.question) %>
            </div>
            <div class= "answer-button">
              <%= link_to new_answer_path(question_id: @question.id), method: :get do %>
               <p class = "btn btn-block btn-white">回答する</p>
              <% end %>
            </div>
            <div class="request-user">
              <% if logged_in? && @question.user_id == current_user.id %>
               <% @question.requests.each do |request| %>
                <p><%= request.user.name %>さんにリクエスト済</p>
               <% end %>
              <% end %>
            </div>
            <div class= "delete-button">
            　<% if logged_in? && @question.user_id == current_user.id %>
              　<%= link_to  question_path(@question.id), method: :delete do %>
                　<%= image_tag 'icons/delete.png', class: 'question-icon' %>
              　<% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <div class="container">
    <% @question.answers.each do |answer| %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
       <div class="question-answer">
         <p class="answer-author">
          <%= link_to answer.user.name ,user_path(answer.user_id) %>
         </p>
         <div class="answer-text">
          <%= simple_format(answer.answer) %>
         </div>
           <div class= "favorite-button">
             <% if !answer.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(answer_id: answer.id, question_id: answer.question_id), method: :post do %>
               <%= image_tag 'icons/heart-black.png', class: 'question-icon' %>
              <% end %>
             <% else %>
              <%= link_to favorites_path(answer_id: answer.id, question_id: answer.question_id), method: :delete do %>
               <%= image_tag 'icons/heart-pink.png', class: 'question-icon' %>
              <% end %>
             <% end %>
            <%= answer.favorite_users.count %>
           </div>
           <div class= "delete-button">
            <% if logged_in? && answer.user_id == current_user.id %>
              <%= link_to  answer_path(answer.id), method: :delete do %>
                <%= image_tag 'icons/delete.png', class: 'question-icon' %>
              <% end %>
            <% end %>
           </div>
       </div>
      </div>
    </div>
    <% end %>
  </div>
</div>