config/routes.rb
Rails.application.routes.draw do
  get 'questions/new'
  get 'sessions/new'
  
  root 'pages#index'
  get 'pages/help'
  
  resources :users do
    member do
      get :following,:followers
    end
  end
  resources :questions
  resources :categories
  resources :answers
  resources :relationships
  resources :requests
  
  #get    'requests/new'
  #post   '/requests', to: 'requests#create'
  #, only: [:create, :destroy]
  
  get    'favorites/index'
  post   '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  root 'question#index'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  
  belongs_to :user
  belongs_to :question
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: 'user', dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :questions
  #has_many :question_categories
  #has_many :questions, through: :question_categories
  #accepts_nested_attributes_for :question_category
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ApplicationRecord
  validates :user_id, presence: true
  validates :question, presence: true
  #validates :category_id, presence: true
  
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :requests, dependent: :destroy
  #has_many :request_users, through: :requests, source: 'user'
  #has_many :question_categories
  #has_many :categories, through: :question_categories
  #accepts_nested_attributes_for :question_categories
end

app/models/question_category.rb
class QuestionCategory < ApplicationRecord
    validates :question_id, presence: true
    validates :category_id, presence: true
    
    belongs_to :category
    belongs_to :question
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, format: { with: /[^\s]@[^\s]\.[^\s]/ }
  validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\Z/i }
  validates :password_confirmation, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\Z/i}
  
  has_secure_password
  
  has_many :questions
  has_many :answers
  has_many :favorites
  has_many :favorite_answers, through: :favorites, source: 'answer'
  has_many :requests
  has_many :request_questions, through: :requests, source: 'question'
  has_many :active_relationships, class_name: "Relationship",
                    foreign_key:"follower_id",
                    dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                    foreign_key:"followed_id",
                    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships,source: :follower
  
  
  
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end
  
  def create
    @answer = current_user.answers.new(answer_params)
    
    if @answer.save
      redirect_to question_path(@answer.question_id), success: '回答を投稿しました'
    else
      flash.now[:danger] = '入力内容を確認していください'
      render :new
    end
  end
  
  def destroy
    answer = Answer.find(params[:id])
    #byebug
    if answer.destroy
      redirect_to question_path(answer.question_id), success: '削除しました'
    else
      flash.now[:danger] = '削除できませんでした'
      render :new
    end
  end

  
  private
  def answer_params
    params.require(:answer).permit(:user_id, :question_id, :answer)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
 
 def index
  @request_questions = current_user.request_questions
 end
 
 def new
   @user = User.find(params[:user_id])
 end
 
 def create
   @request = Request.new
   @request.question_id = params[:question_id]
   @request.user_id = params[:user_id]
   
    if @request.save
     redirect_to user_path(@request.user_id), success: 'リクエストに成功しました'
    else
     flash.now[:danger] = 'リクエストに失敗しました'
     render :new
    end
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to root_path, success: '登録が完了しました'
      else
        flash.now[:danger] = "登録に失敗しました"
        render :new
      end
  end
  
  def show
    @user = User.find(params[:id])
    #@request = Request.find(params[:user][:id])
    #@user = User.find(params[:user][:id])
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/new.html.erb
<div class="answer-new-wrapper">
  <div class="question-index-single">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class= "question-text">
              <%= simple_format(@question.question) %>
          </div>
          <%= form_for @answer do |f| %>
          <div class="form-group">
            <%= f.text_area :answer,:size=>"60x20", class: "form-control"  %>
            <%= f.hidden_field :question_id, :value => params[:question_id] %>
          </div>
          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/requests/index.html.erb
<div class="request-index-wrapper">
  <div class="container">
    <div class="explanation">
      <h1>回答リクエスト受信一覧</h1>
    </div>
    <div class="row">
     <div class="question-index">
      <% @request_questions. each do |question| %>
      <div class="question-index-single">
        <p class="question-author">
          <%= link_to question.user.name , user_path(question.user_id) %>
        </p>
        <p class= "question-category">
          <%= question.category.category %>
        </p>
        <div class= "question-text">
          <%= simple_format(question.question) %>
        </div>
        <div class= "details">
          <%= link_to '詳細', question_path(question.id), class: 'btn btn-block btn-white' %>
        </div>
      </div>
      <% end %>
     </div>
    </div>
  </div>
</div>

app/views/requests/new.html.erb
<div class="request-new-wrapper">
  <div class="container">
    <div class="row">
     <div class="explanation">
      <h1>回答リクエスト</h1>
      <p><%= @user.name %>さんに答えてほしい質問を選択してください</p>
     </div>
     <div class="question-index">
      <% current_user.questions.each do |question| %>
      <div class="my-question">
        <div class="request-question-category">
          <%= question.category.category %>
        </div>
        <div class="request-question">
          <%= question.question %>
        </div>
        <div class= "details">
          <%= link_to requests_path(question_id: question.id, user_id: @user.id), method: :post do %>
           <p class= "btn btn-block btn-white">選択する</p>
          <% end %>
        </div>
      </div>
      <% end %>
     </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
 <div class="bg">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-blue">アカウント作成</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-blue' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-blue' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-blue' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
         <%= f.submit "登録", class: 'btn-block btn-white' %>
          
        <% end %>
       <%= link_to 'ログインはこちら', login_path, class: 'text-blue' %>
      </div>
    </div>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class= "user-show-wrapper">
  <div class= "container">
    <div class= "row">
      <div class="user-show-single">
        <div class="user-show-container">
          <h3 class= "user-name">
            <%= @user.name %>
          </h3>
          <div class="follow-index">
            <%= link_to 'フォロー中・フォロワー' , following_user_path(@user) %>
          </div>
          <div class="follow-button">
           <% unless current_user == @user %>
            <% if current_user.following?(@user) %>
             <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }) do |f| %>
             <%= hidden_field_tag :followed_id, @user.id %>
             <%= f.submit 'フォロー解除', class: 'btn btn-danger btn-block' %>
            <% end %>
           <% else %>
            <%= form_for(current_user.active_relationships.build) do |f| %>
             <%= hidden_field_tag :followed_id, @user.id %>
             <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
             <% end %>
            <% end %>
           <% end %>
          </div>
          <div class="request-btn">
            <% unless current_user == @user %>
             <%= link_to new_request_path(user_id: @user.id), method: :get do %>
              <%= image_tag 'icons/question.png', class: 'question-icon' %>
             <% end %>
            <% end %>
          </div>
          <span class='favorite-index'>
            <% if logged_in? && @user.id == current_user.id %>
             <%= link_to 'いいね一覧', favorites_index_path %>
            <% end %>
          </span>
          <span class="request-index">
            <% if logged_in? && @user.id == current_user.id %>
             <%= link_to '回答リクエスト受信一覧', requests_path %>
            <% end %>
          </span>
        </div>
        <div class="question-index">
          <h4>質問一覧</h4>
           <% @user.questions.each do |question| %>
           <div class="my-question">
            <div class="user-question-category">
             <%= question.category.category %>
            </div>
            <div class="user-question">
             <%= question.question %>
            </div>
            <div class= "details">
             <%= link_to '詳細', question_path(question.id), class: 'btn btn-block btn-white' %>
            </div>
           </div>
           <% end %>
        </div>
        <div class="answer-index">
          <h4>回答一覧</h4>
           <% @user.answers.each do |answer| %>
           <div class="my-answer">
            <div class="user-answer">
             <%= answer.answer %>
            </div>
            <div class="details">
             <%= link_to '詳細', question_path(answer.question_id), class: 'btn btn-block btn-white' %>
            </div>
           </div>
           <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="user-show-follow-wrapper">
  <div class="row">
    <section class="user_info">
      <h1><%= @user.name %></h1>
    </section>
    <div class="following-index">
     <h3>フォロー中一覧</h3>
      <% @user.following.each do |user| %>
      <table>
       <div class="following-container">
         <h4><%= user.name %></h4>
         <p><%= link_to '詳細', user_path(user) %></p>
       </div>
      </table>
      <% end %>
    </div>
    <div class="follower-index">
      <h3>フォロワー一覧</h3>
       <% @user.followers.each do |user| %>
       <table>
       <div class="follower-container" >
         <h4><%= user.name %></h4> 
         <p><%= link_to '詳細', user_path(user) %></p>
       </div>
       </table>
       <% end %>
    </div>
  </div>
</div>