config/routes.rb
Rails.application.routes.draw do
  get 'questions/new'
  get 'sessions/new'
  
  root 'pages#index'
  get 'pages/help'
  
  resources :users do
    member do
      get :following,:followers
    end
  end
  resources :questions
  resources :categories
  resources :answers
  resources :relationships
  resources :requests
  
  #get    'requests/new'
  #post   '/requests', to: 'requests#create'
  #, only: [:create, :destroy]
  
  get    'favorites/index'
  post   '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  root 'question#index'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  
  belongs_to :user
  belongs_to :question
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: 'user', dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :questions
  #has_many :question_categories
  #has_many :questions, through: :question_categories
  #accepts_nested_attributes_for :question_category
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ApplicationRecord
  validates :user_id, presence: true
  validates :question, presence: true
  #validates :category_id, presence: true
  
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :requests, dependent: :destroy
  #has_many :request_users, through: :requests, source: 'user'
  #has_many :question_categories
  #has_many :categories, through: :question_categories
  #accepts_nested_attributes_for :question_categories
end

app/models/question_category.rb
class QuestionCategory < ApplicationRecord
    validates :question_id, presence: true
    validates :category_id, presence: true
    
    belongs_to :category
    belongs_to :question
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true, format: { with: /[^\s]@[^\s]\.[^\s]/ }
  validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\Z/i }
  validates :password_confirmation, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}\Z/i}
  
  has_secure_password
  
  has_many :questions
  has_many :answers
  has_many :favorites
  has_many :favorite_answers, through: :favorites, source: 'answer'
  has_many :requests
  has_many :request_questions, through: :requests, source: 'question'
  has_many :active_relationships, class_name: "Relationship",
                    foreign_key:"follower_id",
                    dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                    foreign_key:"followed_id",
                    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships,source: :follower
  
  
  
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to root_path, success: '登録が完了しました'
      else
        flash.now[:danger] = "登録に失敗しました"
        render :new
      end
  end
  
  def show
    @user = User.find(params[:id])
    #@request = Request.find(params[:user][:id])
    #@user = User.find(params[:user][:id])
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Domanda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
      <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
       <div class="container">
          <h1 class="text-black">domanda</h1>
           <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
            <li>
              <%= link_to questions_path do %>
                <%= image_tag "icons/home.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to user_path(current_user) do %>
                <%= image_tag "icons/my.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_question_path do %>
                <%= image_tag "icons/question.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
            <% end %>
           </ul>
       </div>
      </nav>
    <%= yield %>
    
    <script>
     $(function(){
      $(".alert").fadeOut(5000);
     });
    </script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="bg">
   <div class="container top-hero-container">
    <div class="row">
      <div class="black">
        <%= link_to 'ログイン', login_path, class: 'btn btn-block btn-user' %>
      </div>
      <div class="black">
        <%= link_to 'アカウント作成', new_user_path,class: 'btn btn-block btn-session' %>
      </div>
    </div>
   </div>
  </div>
</div>